#!/usr/bin/env bash

# first argument is the name of the subproject
subproject_name=$1
# change directory
cd subprojects/$subproject_name > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "error: Could not access subproject folder." >&2
    exit 1
fi
# clean (via makefile)
if [ -f makefile ]; then
    make clean > make.log
    # remove make log file
    rm -f make.log
else
    echo "error: Could find makefile." >&2
    exit 1
fi
