#!/usr/bin/env bash

# first argument is the name of the subproject
subproject_name=$1
# OPTIONAL: second argument is a label
label=$2

# build
./build $subproject_name
if [ $? -ne 0 ]; then
    echo "error: Could not build subproject." >&2
    exit 1
fi
# change directory (subproject)
cd subprojects/$subproject_name > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "error: Could not access subproject folder." >&2
    exit 1
fi
# print disassembly of executable
if [ -f bin/main ]; then
    # otool options:
    # t : teyt section
    # d : data section
    # V : display as symbols (not as bytes)
    if [ -z "$label" ]; then
        otool -tdV bin/main
    else
        otool -tdV bin/main -p $label
    fi
else
    echo "error : Could not find executable."
fi
