#!/usr/bin/env bash

# first argument is the name of the subproject
subproject_name=$1

# build
./build $subproject_name
if [ $? -ne 0 ]; then
    echo "error: Could not build subproject." >&2
    exit 1
fi
# change directory (subproject)
cd subprojects/$subproject_name > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "error: Could not access subproject folder." >&2
    exit 1
fi
# change directory (bin)
cd bin > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "error: Could not access subproject's bin folder." >&2
    exit 1
fi
# run (forward arguments)
./main "${@:2:99}"
ret=$?
if [ $ret -ne 0 ]; then
    echo "warning: Executalbe stopped with exit code $ret." >&2
    exit $ret
fi
