#!/usr/bin/env bash

# first argument is the name of the subproject
subproject_name=$1

# build
./build $subproject_name
if [ $? -ne 0 ]; then
    echo "error: Could not build subproject." >&2
    exit 1
fi
# change directory (subproject)
cd subprojects/$subproject_name > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "error: Could not access subproject folder." >&2
    exit 1
fi
# print symbol table of executable
if [ -f bin/main ]; then
    echo "address scope symbol"
    echo "--------------------"
    nm bin/main
else
    echo "error: Could not find executable."
fi
